# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Docker Login
description: Login to ghcr.io and optionally dhi.io
inputs:
  dhi-username:
    description: dhi.io username
    required: false
    default: ""
  dhi-token:
    description: dhi.io token
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Login to dhi.io
      if: ${{ inputs.dhi-username != '' }}
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: dhi.io
        username: ${{ inputs.dhi-username }}
        password: ${{ inputs.dhi-token }}
