# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Changed Images
description: Select images that were updated in PR

outputs:
  changed-images:
    description: List of changed images
    value: ${{ steps.changed-files.outputs.all_changed_files }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
      with:
        diff_relative: "true"
        path: images
        files: "**"
        dir_names: true
        matrix: true
        files_ignore: "**/*.md"
    - name: List all changed files
      shell: bash
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
