# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Changed Images
description: Select images that were updated in PR

outputs:
  changed-images:
    description: List of changed images
    value: ${{ steps.changed-files.outputs.all_changed_files }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@7dee1b0c1557f278e5c7dc244927139d78c0e22a # v47.0.4
      with:
        diff_relative: "true"
        path: images
        files: "**"
        dir_names: true
        matrix: true
        files_ignore: "**/*.md"
    - name: List all changed files
      shell: bash
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
