# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Changed Images
description: Select images that were updated in PR

outputs:
  changed-images:
    description: List of changed images
    value: ${{ steps.changed-files.outputs.all_changed_files }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
      with:
        diff_relative: "true"
        path: images
        files: "**"
        dir_names: true
        matrix: true
        files_ignore: "**/*.md"
    - name: List all changed files
      shell: bash
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
